# Files that Aider should read to understand the project
read:
  - README.md
  - docs/CONVENTIONS.md

# Enable prompt caching to improve performance
cache-prompts: true

# Keep connection alive with pings
cache-keepalive-pings: 5

# Model settings
model: claude-3-5-sonnet-20241022
#temperature: 0.0

## Editor settings
#edit-format: simple
#line-numbers: true
#
## Git settings
#git-add: true
#git-commit: true
