# Files that Aider should read to understand the project
read:
  - README.md
  - docs/CONVENTIONS.md

# Enable prompt caching to improve performance
cache-prompts: true

# Keep connection alive with pings
cache-keepalive-pings: 5

# Editor settings
edit-format: simple
line-numbers: true

# Git settings
git-add: true
git-commit: true

# Model settings
model: claude-3-sonnet-20240229
temperature: 0.0
